### ISSUE TITLE
`push` to export fails with old git-annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#104]
Quick notes on seeing it live in a screenshare. `git-annex` was 8.20200617. `push` (as patched with `-next` failed at https://github.com/datalad/datalad-next/blob/c97a84ff7e5e58493a4eec04a620b72c0d9ba5e7/datalad_next/patches/push_to_export_remote.py#L226-L227

because that version of git-annex emitted a JSON record with `{..., file: None}` (unclear wheter it was a real `None` or the string `"None"`.

The patched push triggered it, but this might be really a bug in `annexjson2result()` from core... Although

```py
    if d.get('file'):
        res['path'] = str(ds.pathobj / PurePosixPath(d['file']))
```

the failing code (i.e. `Path / Path`) should only be reached if there is no path.

Upgrading to a recent git-annex changed its behavior and no longer triggers the issue.

@mslw may have additional info.

Given that we have little chance to debug this, we might want to close this with a warning if such an old version is used in that code. The `datalad-annex::` code might also provide an even stricter version requirement that also deserves such a check.

**Comment by mslw** [comment]
> Given that we have little chance to debug this, we might want to close this with a warning if such an old version is used in that code. The datalad-annex:: code might also provide an even stricter version requirement that also deserves such a check.

Since the warning has been added, I do not see anything else that can be done. I'll close this.
