### ISSUE TITLE
Let `CredentialManager` ask for a credential name if not given

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#130]
or maybe `credentials()` should do that. Right now, each code piece that wants to save a new credential must implement some logic to auto-determine a name.

But if a new credential was entered, we are running interactively anyways. Why not have the user enter a name at that time, rather than having to live with a complex auto-generated one (they are complex, because they want to avoid collisions).

The only way right now to avoid this, is to anticipate a missing credential and use `--credential` upfront. That kind of "planning ahead" is needlessly demanding and easily avoidable IMHO.

Update:

I think this can be implemented directly in the `credentials` command. If `action=='set'` and there is not `name` given, prompt for one.

Any command that relied on the previous behavior (an exception) is pretty much guaranteed to be providing an auto-generated name to begin with. They could optionally stop doing that. Any new command could make use if the prompting and not have to worry about this complexity.

Moreover, such command could then catch and ignore the `ValueError` caused by a user deciding not to provide a name, and gracefully continue simply without saving the credential -- which might very well be the desired outcome of a user.

**Comment by mslw** [comment]
Overall, a +1 from me. When I started using the credentials command it felt easier for me to use explicit names or even specify the credential upfront (it's impossible to edit the default credential names through CLI without an awkward copy-paste of the names).

> Any command that relied on the previous behavior (an exception) is pretty much guaranteed to be providing an auto-generated name to begin with. They could optionally stop doing that. Any new command could make use if the prompting and not have to worry about this complexity.

If it comes to prompting, would it be possible to use the auto-generated name as default, as in: "Credential name (default: foo.bar.baz):"?

I wonder if any of these commands relies on the credential name when finding a matching one (when `--credential` is not used explicitly)? I would guess not, but if they did then my suggestion above wouldn't work well, because something that matters would get overridden.

**Comment by mih** [comment]
With the changes proposed in https://github.com/datalad/datalad-next/commit/c574ac76813d91c8ef1a66476991bcf3eb886d0c it makes sense to change the desired behavior of any `--credential` parameter.

- if given, an existing credential is looked up and used if it exists. The implementation of an `EnsureCredential` is then possible and desirable. If an identified credential does not exist, processing stops at the parameter validation state.
- if not given, internals try to determine a suitable credential (also needed when a single credential is insufficient. think downloads from multiple sources)
- if not given, and no credential could be auto-identified, a user is prompted for a credential. This can happen deep inside the machinery. Once validity of a newly entered credential is confirmed, it is attempted to be saved by `CredentialManager.set()` -- with `name=None`. A name suggestion can be given via `_suggested_name`. Context info can be given via `_context` to help a user understand what credential is attempted to be saved. A user can reject the credential storage (it would make sense to introduce a general config flag for that).
