### ISSUE TITLE
Exception conventions for `UrlOperations`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#154]
This functionality replaces the datalad-core downloader framework. However, the old exceptions are no good fit anymore. I think is is time to  access the different states and assign proper exceptions to each. The challenge is to be as precise as possible, but also acknowledge that particular methods may have different ability to distinguish individual reasons for failure.

We need a new base exception. `DownloadError` makes no sense for a system that can also perform uploads.

The exception semantics need to make sense across different protocols:

- HTTP
- SSH
- FILE (e.g. local FS operations)

Scenarios:

- System access fails (possibly the whole things, not just an individual URL target)
  - Examples:
    - HTTP403
    - SSH login fails
- Accessing the target location of a URL within a system fails
  - Example:
    - HTTP403
    - `cp` lacking read/write permissions
    - missing read/write permissions server-side

**Comment by mih** [comment]
Point (1) is addressed already.

Point (2) makes sense, and should already be the case.

I will leave (3) uncommented for now. But re (4) I'd say that it will be difficult to make such specific distinctions in practice. Not so few systems, for example, give HTTP404 when accessing a resources without proper permissions (because even knowing that it exists can be an issue). Hence I was aiming to discriminate access failure on a general level (network down, server unavailable) from specific resource access failure.

None of that applies to local errors. They could be precise.

**Comment by christian-monch** [comment]
My 2 cents: 
I think we agree to aim to minimize the number of new errors we introduce. I identified a number of different errors in three categories (roughly corresponding to the local software interface, the transport stack, and the remote system):

- *General Transport Error* (timeout based: no connection, no data transport, no response, ...)

- *Resource Unknown Error* (unknown hostname, no such file, ...)
- *Resource Connection Error* (no route to host, connection rejected)

- *Client Authentication Error* (invalid credentials)
- *Client Authorization Error* (not authorized, or not authenticated)

Especially the last two, *Client Authentication Error*, and *Client Authorization Error*, can be difficult to distinguish if they are signaled by the remote host, for example in HTTP.  They could be combined into a general *Client Access Error*. The main question would be whether it makes sense for the user of `UrlOperations` to be able to distinguish them. A user might in any such case be required to parse some error description.

It seems to me that we only need to define errors that are generated by the transport system. For all local errors, it would make sense to use existing exceptions, e.g. `FileNotFoundError`, `FileExistsError`, `PermissionError`.

To unify the errors we could define `UrlOperationErrors`, `raise` local errors `from` a derived class `UrlOperationsLocalError(UrlOperationsError)`, and define all the above errors as subclasses of `UrlOperationsRemoteError(UrlOperationsError)`.

Long text! To summarize:
```
class UrlOperationsError(Exception):
    pass

class UrlOperationsLocalError(UrlOperationsError):
    pass 

class UrlOperationsRemoteError(UrlOperationsError)
   pass

class UrlOperationsTransportError(UrlOperationsRemoteError):
   def __init__(self, to_url, error_message):
        ...

class UrlOperationsResourceUnknownError(UrlOperationsRemoteError):
   def __init__(self, to_url, resource name):
        ...

class UrlOperationsResourceConnectionError(UrlOperationsRemoteError):
   def __init__(self, to_url, remote_message):
        ...

class UrlOperationsClientAuthenticationError(UrlOperationsRemoteError):
   def __init__(self, to_url, credential_id, remote_message):
        ...

class UrlOperationsClientAuthorizationError(UrlOperationsRemoteError):
   def __init__(self, to_url, credential_id, remote_message):
        ...
```

Just a suggestion. Not sure how far from the target this hits ;-)

**Comment by christian-monch** [comment]
I think when it comes to string-parsing vs structured error description, there is no easy way to get around string-parsing when dealing with remote errors. But the proposal above handles remote messages transparently and leaves the parsing to the user of `UrlOperations`.

**Comment by mih** [comment]
Selective response to

> The main question would be whether it makes sense for the user of UrlOperations to be able to distinguish them. A user might in any such case be required to parse some error description

The main use case I know is git-annex special remote CHECKPRESENT. It is being able to say with confidence "this remote does NOT have this resource" vs "i cannot say whether a remote has the resource" (because it is not accessible as a whole right now).

**Comment by christian-monch** [comment]
> Selective response to
> 
> > The main question would be whether it makes sense for the user of UrlOperations to be able to distinguish them. A user might in any such case be required to parse some error description
> 
> The main use case I know is git-annex special remote CHECKPRESENT. It is being able to say with confidence "this remote does NOT have this resource" vs "i cannot say whether a remote has the resource" (because it is not accessible as a whole right now).

So we are talking about distinguishing a valid result, which might be positive ("I have the resource") or negative ("I don't have the resource") from the inability to get a valid result? At least that is how I understand the comment, maybe I don't have enough context w.r.t. git-annex special remotes and where in the code-paths "CHECKPRESENT" would be used. But I would assume that the result of a call like `a_remote.checkpresent(some_key)` would return `True` or `False` if the presence of the resource could be determined. If the presence could not be determined, it could signal that by a third value or probably by raising an exception, Although I think an exception might not be the mechanism of choice here, because it is known and expected that a remote might not support CHECKPRESENT. If none of the above applies, an exception could be raised, but that situation would only occur if some unpredicted error condition applies. Am I missing something?

**Comment by mih** [comment]
That is exactly how it needs to work. The third value is a particular exception (`RemoteError`) that the `AnnexRemote` harness turns into the desired signaling for git-annex.

**Comment by mih** [comment]
Trying to take it all in, and aiming for a minimal workable solution. What about this:

```
class UrlOperationsRemoteError(Exception)
   def __init__(self, to_url, error_message):
        ...
```
Base class. Specifically saying that we are only creating a collection of exceptions for non-local errors. For local ones, we have a large collections of recognized exceptions type that enable fine-grained handling (e.g. `FileNotFoundError`, `PermissionError`, etc). This exception always carries information on the remote URL.

When *anything* goes wrong with the remote, client code can intercept this exception type.

The rest are specialized errors, for which we foresee utility.

```
class UrlOperationsResourceUnknownError(UrlOperationsRemoteError):
```

`RemoteFileNotFound`, `HTTP404` type exception.

```
class UrlOperationsConnectionError(UrlOperationsRemoteError):
```

Connection dropped, network down, host not found. If ever needed, could be a base class for more detailed types. For now, just one specialization:

```
class UrlOperationsAuthenticationError(UrlOperationsConnectionError):
   def __init__(self, to_url, credential, remote_message):
```

Any `HTTP401` type error, i.e. credential missing/wrong, session expired etc. We generally may not have a meaningful ID for a credential. We could include whatever credential information we have in a dict(?)

```
class UrlOperationsAuthorizationError(UrlOperationsRemoteError):
   def __init__(self, to_url, credential_id, remote_message):
```

Any `PermissionDenied` type error. Importantly, this is not a `UrlOperationsConnectionError`. It is meant to also capture any resource access permission errors after a general connection could be established. 

WDYT?

**Comment by bpoldrack** [comment]
Seems OK to me.

Only point I see is that a caller, like a special remote, that in principle works with any URL including `file:`, needs special code for this type of URL merely for error handling. Because `except` clauses need to catch completely different exceptions in this case. All other code at this layer may not care the least about the type of URL. That's not beautiful, but it may be OK in practice.

**Comment by bpoldrack** [comment]
> Can you elaborate why? The "remote" end of a file:// URL is treated the same as for any other scheme.

If that is so, then my comment is not valid for the caller. But it would imply, that there's code operating locally, that is aware that it is the "remote end" and raises `UrlOperationsRemoteError` from `FileNotFoundError`, `PermissionError`, etc.
I'm not sure what that code is (but I didn't pay too close attention to next recently).
If that unification is expected to be done, then why would it be so terrible to also have that same unification for the local end and have `UrlOperationsLocalError` ?

**Comment by bpoldrack** [comment]
@mih 

So, go ahead. What I said is not contradicting your suggestion. It would be an addition that could still be done, if we find there actually is a case where it becomes relevant.

**Comment by mih** [comment]
> To me, a `UrlOperationsAuthenticationError` seems more like a sibling of `UrlOperationsAuthorizationError`. Both are created in the same layer and, to a certain degree, independent of the transport layer. Maybe I interpreted to explanation wrongly.

I think that is a valid view. My thinking was: Without a valid authentication, there is no "connection" to work with for performing the desired operation. Likewise, for connection-less operations (e.g. on `file://` URLs) there cannot be a connection error, and also consequently no authentication error (because there is none) -- but there surely can be authorization errors.

So while you are correct, I am not sure whether that nothing of "same layer" is important or relevant for implementing client code.

**Comment by christian-monch** [comment]
> Maybe "connection" is the wrong term here. It is more like "establish a working environment to perform the target operation in or on".

I think my interpretation of "Connection" was probably too much informed by the ISO-OSI layer model, where it is a technical connection between two corresponding protocol machines. If I interpret it instead as "working environment establishment", the hierarchy you describe makes sense. 

From my point of view, it seems like a sensible and useful error handling concept

**Comment by mih** [comment]
OK, so we should find a better term than connection. `UrlOperationsRemoteEnvironmentError` is the best I can do, and I don't like it.

**Comment by christian-monch** [comment]
We can leave it at connection, but if we want to go for a another term, how about: `UrlOperationInteractionError` `UrlOperationCooperationError`, or `UrlOperationCommunicationError`? 

Just to be clear, I don't object to using the term "connection". We are free to interpret it in our way and my default-interpretation might be the exception rather than the rule.

**Comment by mih** [comment]
`UrlOperationInteractionError` clicks with me.

`UrlOperationCommunicationError` sounds more standard, but maybe it would be unexpected to have an `AuthenticationError` be a specialization of it. But maybe not.

**Comment by mih** [comment]
Implementing this now

**Comment by mih** [comment]
Ah, stumbled immediately upon `TimeoutError`. It feels as if this should now be derived from `UrlOperationsInteractionError`, but it also feels wrong to redefine this basic type. It probably needs to stay a dedicated thing to be handler separately and (likely) differently than any other (unspecific) remote error.
