### ISSUE TITLE
Consolidate matching siblings-finding between create_sibling_ria and create_sibling_webdav

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-next#17]
`create_sibling_ria` has code to determine matching siblings. Currently `create_sibling_webdav` has a function that does similar things, i.e. `_yield_ds_w_matching_siblings`.

Once the functions is perfected, the implementations should be consolidated. That means the function should probably move to core and be used by both sibling implementations.

(This issue replaces a TODO in `create_sibling_webdav.py`

**Comment by mih** [comment]
This is the companion in -core (where it would need to be fixed): https://github.com/datalad/datalad/issues/6644

Closing this one. Thx!
