### ISSUE TITLE
Implement `ArchiveOperations`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#184]
Analog to `UrlOperations` but for creating and extracting from archives of any kind.

There a various implementations in datalad-core for this. Direct use of `tarfile`, `zipfile`, a `7z` wrapper, a `patool` wrapper. The main operations supported are `compress_file` and `decompress_file` (note the single-file granularity). For performance reasons, there is also a caching layer built around this to make extracting more than one file faster, at the expense of diskspace consumption.

I think we can apply the same concept as for `UrlOperations` -- a handler per archive type(combination), plus a set of operations.

- `extract`
- `extract_all` (to be efficient, when it is known that we need all)
- `add`
- `create_from` (to be efficient, when it is known that we just need to ingest some blobs into a new archive)

Whether or not to keep extracted copies around for caching, or do other maintenance or cleanup operations would be a configuration of the handler (or the task of alternative handlers).

In order to optimally support something like #183 , it would be good to provide an archive content iterator too.

Survey of archive operations in the datalad codebase:

- `datalad.local.export_archive`: Wrap `tarfile/zipfile` to create an archive from scratch, with timestamp customization.
- `datalad.distributed/export_archive_ora`: Create a `7z` archive from scratch (with annex keys), only `7z`-native customization options supported.
- `datalad.support.archive_utils_7z`: extract and add single files to an archive (within ArchiveCache framework)
- - `datalad.support.archive_utils_patool`: extract and add single files to an archive (within ArchiveCache framework)
- `datalad.distributed.ora`: extract a single file from a `7z` archive
- `datalad.customremotes.archives`: Extract a single file from an archive (within ArchiveCache framework)
- `datalad.distributed.export_to_figure`: Create archive from scratch using `export_archive`
- `datalad_next.gitremotes.datalad_annex`: create an zipfile from scratch, and fully extract all content from a zipfile
- `datalad_ukbiobank.update`: Index all zipfile content via `add-archive-content`
- `datalad_osf.git_remote`: create an zipfile from scratch, and fully extract all content from a zipfile

**Comment by bpoldrack** [comment]
> Whether or not to keep extracted copies around for caching

Just leaving a reminder, that potential extraction cache location(s) should be made known to `datalad clean`.

**Comment by mih** [comment]
Right now, I do not see why there should be *persistent* caches that would need cleaning up. AFAICS we need a common cache to have multiple processes by able to take from it (in some situations), but I do not see why they would not be cleaned up by the last exiting process.

That being said, I would aim for no change re location to make any such modifications to `clean` unnecessary.

**Comment by mih** [comment]
Discussion with @yarikoptic led to another useful distinction: `LocalArchive` vs `RemoteArchive`. The latter could have a number of subclasses to deal with different archive types, or possibly combinations of "remotes" and archives types. These particular implementation could provide support for https://github.com/datalad/datalad/issues/373 in a number of supportable cases, using different solutions (mounting remote FS, streaming parts of a file with some offsets, etc). Analog to `UrlOperations` there could be a dedicated `AnyRemoteArchive` or even `AnyArchive` that implements the logic for selecting to best implementation for a given archive+platform+transport.

**Comment by mih** [comment]
#384 provides a starting point for all this, and an initial API with a demo implementation. It is focused on reading, not writing archives.
