### ISSUE TITLE
Structured error reporting for `EnsureCommandParameterization`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#198]
ATM the encoding of validation errors and correction hints can be overwhelming for more complex constraint setups. There should be an option (or default) to get structured reports that could be rendered in different (environment-optimized ways), e.g. as an input form annotation in a GUI.

**Comment by mih** [comment]
The most meaningful approach (known to me) for this is pydantic's `ValidationError`: https://docs.pydantic.dev/usage/models/#error-handling

**Comment by mih** [comment]
I looked into https://docs.python.org/3/library/exceptions.html#exception-groups (backport available at https://pypi.org/project/exceptiongroup/).

This is not applicable directly, because it is location the subject of a constraint violation (we must know which parameter is wrong, not just that any parameter is wrong in a particular fashion). However, exception groups are essentiall exceptions that contain other exceptions (in a tuple). For the purpose here it would be sufficient to contain them in a mapping that associates an arbitrary key, representing the context, with the associated exception.

In the scope of a command parameter constraint the keys would be `str` matching parameter names (and possibly name special names for, e.g., joint-validation).

**Comment by mih** [comment]
Some thoughts:

When I need to validate a single value, key bits of information when that validation fails would be 1) what was the violated criterion, and 2) what value violated it. Presently, we encode (1) in a handcrafted message that should also include (2) But sometimes it doesn't.
I am thinking to have a `ConstraintError` that is the base exception for all this. And I am debating what arguments its constructor should have.

Concept:

- it should receive the original input value -- to make it uniformly available for inspection reporting, etc. 
- it should receive some kind of error message -- strictly focused on the key violation. With that focus, and known that the original value need not (necessarily) be included in it (because it is also available), I suspect that reporting can be more stringent, and its verbosity better configurable from the outside
- it should also receive the violated constraint (instance). This would enable a reporting function to retrieve the necessary info for doing: "This error happened" + "because you provided X" + "here is what would have been acceptable"

This would clearly assign responsibilities to the underlying code. The constraint must be able to state clearly what is valid input, and can report compactly on what criterion was violated (without having to say in the message what value violated it -- the message could become more label-like). The `ConstraintError` would then bind all (message, input, constraint) together to make it jointly accessible -- avoiding the need for external tracking logic.

Raising a ConstraintError from a Constraint would then look like `ConstraintErrorDerived(self, msg, value)`

**Comment by mih** [comment]
Consider this example:

```
cmd(a=5, b=6, c=6)
```

where the constraints assigned to the parameters are:

- `a`: `EnsureInt() & EnsureRange(max=3)`
- `b`: same as for `a`
- `c`: `EnsureInt() & EnsureRange(min=7)`

This means the constraints for all three parameters are violated. How could be report this clearly (without given a user a research task), when we have one and the same constraint violated in the same way, but for two different values, in two different contexts (parameters); and we also have two different constraints violated by the exact same value in two different contexts.

Any approach along the lines of "we infer this from the traceback" is IMHO either fragile, or hardly capable of communicating what is needed here. And that is:

- `a` must not be larger than 3 (got 5)
- `b` must not be larger than 3 (got 6)
- `c` must not be smaller than 7 (got 6)

The basic `ConstraintError` is just a ValueError with some additional info. Importantly, it cannot know about the context (above we use the same constraint twice for two different applications). Coercion or type conversion are useful and a target use case outside command parameter validation, so making thing specific for this one use case is not desirable.

> why would the individual exceptions not contain sufficient information already

I think my answer would be: I don't know how they could. At least not without building something that can only be used for command parameter validation.

**Comment by mih** [comment]
An idea:

With #234 `ConstraintErrors` is a single exception that actually is comprised of multiple underlying exceptions. While this is necessary (see above), it would still be nice to make this as pythonic as possible. One possibility would be to take the list of exceptions (`dict.values()`) and create an `ExceptionGroup` from it, and then use that as the `__cause__` of the `ConstraintErrors` instance.

**Comment by christian-monch** [comment]
> Any approach along the lines of "we infer this from the traceback" is IMHO either fragile [...]

(Thumbs up) I would never argue for such an approach either!

> I think my answer would be: I don't know how they could. At least not without building something that can only be used for command parameter validation.

Thanks for the explanation (I wrongly assumed that the constraint validators would be associated with parameter names and could report them).
