### ISSUE TITLE
Add a dataset ID check for EnsureDataset?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-next#272]
In the context of metalad, I came across other custom checks that may make sense to integrate into existing Constraints. One custom additional check metalad does is a check for a valid dataset ID. Could ``EnsureDataset()`` get a check like this? Or should the constraints not get overloaded with options?

**Comment by mih** [comment]
This makes sense to me. Will do or happily accept a PR for that.

**Comment by christian-monch** [comment]
Just want to mention that there are some datasets that do not contain IDs. This holds, for example, for some datasets in datasets.datalad.org. Not sure how many of those unicorn datasets exist

**Comment by mih** [comment]
There is no requirement for a `Dataset` to have an ID. There is also no requirement for a repository to only contain one dataset (as in unique ID). So all these more uncommon, but perfectly possible combinations have to be expected.
