### ISSUE TITLE
Consolidate "traverser" from gooey and metalad into a common implementation

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#323]
This implementation should be layered, to be useful for listing, but also status/diff reporting.

It should also be benchmarked, relative to git-lsdir and and git-ls-tree.

Ping @christian-monch

**Comment by christian-monch** [comment]
Will get to that in July

**Comment by mih** [comment]
Looking into this further, it seems that it might be more meaningful to replace the implementation of change-detection in gooey's `status-light` which and iterator around `git diff-index HEAD` (instead of the present `diff-files`).

**Comment by mih** [comment]
#580 now also adds `iter_gittree()` to the list of available iterators.

**Comment by mih** [comment]
I have implemented a draft of `iter_gitdiff()` now.
