### ISSUE TITLE
Adjust `ConfigManager` to post overrides into the ENV

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#325]
Overrides can come in via the CLI, or be directly set in a manager instance. Given that overrides are somewhat global, it makes sense to post them in the processes ENV too.

Here is a concrete example of where that would be useful https://github.com/psychoinformatics-de/knowledge-base/issues/15#issuecomment-1522907177 (instead of having to go git-native, a declaration via `datalad -c ...` would be sufficient).

This would also make a runner-specific change to pass on configuration, as proposed in https://github.com/datalad/datalad/pull/7344 (see issue https://github.com/datalad/datalad/issues/7352) unnecessary. While this would work as a solution for the clone issue linked above too, it would be limited to execution via the datalad runner. Simply posting overrides in the process ENV via `GIT_CONFIG_COUNT= GIT_CONFIG_KEY_ GIT_CONFIG_VALUE_` would be applicable to any means of executing subprocesses (e.g., plain `subprocess.run` -- something that is even done in the datalad codebase).

Issues this would address

- https://github.com/datalad/datalad/issues/3456 (closed but unresolved)
- https://github.com/datalad/datalad/issues/4119

#### Interference with Git

If the Git-native variables are already present in the environment (see above), we need to ensure that any DataLad modification amends the existing setup and does not strip settings.

#### Override semantics

The nature of "overrides" in the datalad configuration is underspecified. Relevant statements from the documentation are:

- environment variables can be used to override any datalad configuration, and have precedence over any other configuration scope (any further elaboration is specific to `DATALAD_*` type variables.
- re `DATALAD_CONFIG_OVERRIDES_JSON`: f both individual configuration variables *and* JSON-overrides are used, the former take precedent over the latter, overriding the respective *individual* settings from configurations declared in the JSON-overrides
- the `configuration` command is not able to query overrides separately
- `ConfigManager` docs say: 'override' limits the modification to the `ConfigManager` instance, and the assigned value overrides any setting from any other source [remark: the use of "instance" is a concern here]
- `ConfigManager` declares: Each instance carries a public `overrides` attribute. This dictionary contains variables that override any setting read from a file. The overrides are persistent across reloads [remark: limitation to "from a file" is relevant here]
- CLI config overrides (`datalad -c`) become `ConfigManager` instance overrides

#### Potential inconsistencies

- on `ConfigManager.reload()` instance overrides are applied unconditionally to the "merged" config. But overrides from ENV only when `scope` is not `branch`.  `ConfigManager.get_from_source()` implemented the same logic.
- `ConfigManager` runs `git config`. If `GIT_CONFIG_COUNT= GIT_CONFIG_KEY_ GIT_CONFIG_VALUE_` are declared, this should apply these git-native overrides, but datalad "sees" them. It needs to be checked whether scope associations are inferred properly. Possibly, `ConfigManager` could afterwards simply replace these settings, because it did already "read them in".
  - No, that is not possible. The settings are "seen" (git-config reports them as origin='command line' , and the config manager umps them all into a `git` category. At this point they are no longer detectable as overrides. If the git-nativ declaration is then replaced, any sub-process will no longer get to see them, because they only live in the parent process's `ConfigManager`
- Overrides from ENV are not reported by `ConfigManager.repr()` (only instance overrides)

#### Threats

If the implementation is changed to post config overrides in git-native format into the ENV, we blur the distinction between ENV-overrides (cannot be manipulated via the `ConfigManager`, are applied differently than instance overrides), and instance/CLI overrides. Essentially, any instance override would affect the ENV. However, posting in Git-native format does not simply remove the distinction of instance and ENV overrides (although that may be desirable, given the complexity increase).

It remains to be evaluated, how git-native overrides interact with the attribution of origin of a configuration. Importantly, Git distinguished a dedicated scope `command` for this (separate from `system`, `global`, `local`, `worktree` (which would be most similar to our `branch`)). For this `command` scope, git-config says:

> These environment variables will override values in configuration files, but will be overridden by any explicit options passed via `git -c`

This is both similar and different from our notion of overrides. Yes, they are overrides, but CLI setting has the last word, whereras in datalad, we have ENV override CLI.

The latter could be aligned by the datalad CLI resorting to posting its `-c` setting via the Git-native mechanism into the ENV. This would give them the highest precedence for datalad-internal processing too. It would also allow for a declaration of any `datalad -c X`, in exactly the same way and with the same semantics as `git -c X`, and also result in any internal git call to behave as if called in that fashion.

**Comment by yarikoptic** [comment]
Sorry, I have not fully understood the entire body of analysis yet but I agree (which IIRC aligns with what I proposed in those issues) with the idea of 

> Given that overrides are somewhat global, it makes sense to post them in the processes ENV too.

Since `ConfigManager` is within datalad core -- shouldn't this issue be filed/resolved there?

**Comment by mih** [comment]
> Since `ConfigManager` is within datalad core -- shouldn't this issue be filed/resolved there?

Yes, once it is known how it can be resolved, and what components are affected in which way by that resolution (see above), it should result in a change in datalad-core.

**Comment by mih** [comment]
There seem to be many ways to tweak the current setup to become more comprehensible. I will post sketches of the possibilities as I get a chance to write them down.

### Solution 1: Recognize `command line` origin items as overrides

At present anything that is reported by `git config` as origin `command line` has its origin ignores. Only origins that correspond to files or git-blobs are reported.

This could be changed to actually gather and return these items. A possibility would be to have `parse_gitconfig_dump()` to report them in its second return value. This is a set of "origins" that can contain two types

- for actual files a Path
- for a git-blob a Git blob ID prefixed with 'blob:'

We could extend that to return a `dict` with any config items that came in with `command line` origin.

`ConfigManager.reload()` executes this function and could move these items into its `overrides` dict. It this point any further handling of overrides would be uniform, and also include Git overrides.

`ConfigManager.reload()` runs frequently. So when we start posting overrides into the process ENV, we need to consider serial effects. If a user explicitly sets an override via a `ConfigManager` instance, they expect that override to affect to `override any setting read from a file`. By posting it in the ENV, we need to make sure that any `DATALAD_` ENV overrides would still override such an "instance override". However, the current implementation would/should already achieve that.

**Comment by mih** [comment]
There is a further complication re posting overrides in the ENV: We can only post `str`-type values. This should be fine in principle (without explicit type-casting anything from git-config is `str`), however, right now the `ConfigManager` API/docs do not make this explicit (require `str`), and even our own tests use non-`str` values.

I believe that this can simply be tightened. Any real code that is normally receiving input from git-config must be able to deal with `str` already.

**Comment by mih** [comment]
Another complication: once we posted our overrides into the ENV, we can no longer distinguish between internal and external overrides. For example, if we initially have an override in `ConfigManager` and we later remove it, we also have to forcefully adjust the ENV with that removal -- otherwise anything previously posted into the ENV would return (on `reload()`) after the removal, as a seemingly "external" override.

Solution 1:

I think the loading from the ENV should only be done once at the initial bootstrapping of a config manager. At that stage, ENV overrides should be superimposed with the instance overrides at that point, and the merged dict is then stored as the instance overrides from the moment onwards.

Solution 2:

All setters that support scope `override` must be updated to also adjust the ENV. This could be achieved by replacing the `self.overrides` dict with a custom class that supports the dict API, but performs the ENV manipulation in-sync.


Solution 2 has one attractive aspect: When we post overrides into the ENV, we can easily get into the situation that multiple `ConfigManager` instances compete re ENV manipulation. If a `ConfigManager` only reads the ENV once and then reposts whatever it itself knows about override manipulation (solution 1), we will quickly see disjoint sets of config setting alternative, whenever different managers are active. Solution 2 is more expensive, but would keep any `ConfigManager` connected to ENV manipulation done elsewhere (on reload), and the full set of overrides becomes accessible through any manager too.

**Comment by mih** [comment]
Few notes on the approach:

- `class _ConfigOverrides(UserDict):`
- look into `--show-origin` for getting output from git config -- and maybe filter ENV out?
- let `_ConfigOverrides` parse the ENV on a reload
- possibly preserve types for overrides given via Python (for a particular manager instance)

**Comment by mih** [comment]
So this turns out to be rather complex with loads of side-effects. Not good. What the ConfigManager does and does not is also twisted and worthy of a rewrite (#397). But maybe there is another way....

What problems are we trying to solve exactly:

1. `datalad -c ...` should behave like `git -c` and affect all child processes too
2. ideally setting an override in a `ConfigManager` is actually effective for changing *any* configuration, and not just for datalad-specific with the same (Python) process

What makes this conceptually challenging is that `ConfigManager` maintains its own instance state for overrides. But only for overrides (everything else is written through and has no effect until a `reload()`. This makes overrides instance-specific -- which by definition limits the impact to a within-process scope.

That being said, (1) is easy to solve. On CLI startup, parse the overrides (even outside the `ConfigManager`, post them into the ENV. Done. Anything given to `datalad -c` will be in effect for the entire session, including subprocesses.

Problems would arise, if such overrides would also be reflected in the session config managers (`datalad.cfg`) *as overrides* rather than whatever Git reports as effective configuration. It would be a problem, because then instance method calls like `.remove_section(..., scope='override')` would somehow needed to be acted on, and consolidate the ENV -- but in a general situation where multiple `ConfigManager` instances could perform such modifications between to calls to `reload()`. This is quite complex.

So (1) is solvable whenever we declare `ConfigManager.overrides` to be instance-specific without any impact outside that scope.


(2) is more tricky, because it is a generalization of the override manipulation problem described above. However, it would be solvable if we declare what scope exactly is impacted, and it cannot be the global process environment (for the reasons given above).

What would be doable is to have the overrides of dataset-bound `ConfigManager` instances impact the environments of all subprocesses executed via its `._git_runner` instance. For that we would need to link such a `ConfigManager` to the respective `GitRunner` instance, or we hook into the `env=` argument that is passed to each `.run()` in the `call_git|annex*()` methods.

In both cases, the `ConfigManager.overrides` are *never* set from anywhere other than explicit manipulation via the `ConfigManager` instance. They *do not* reflect any potential Git config overrides in the surrounding ENV. Impact scope re subprocesses is not defined or decided by `ConfigManager`, but by whatever is actually starting the subprocess.

Implementation option

The simplest approach that I can see is therefore completely unrelated to the `ConfigManager`.

- on CLI startup: read `-c`, merge them with any Git config ENV overrides, and repost them to the ENV before anything else happens. Possibly include `DATALAD_CONFIG_OVERRIDES_JSON` in that procedure.
- enhance `Runner.run()` with a `cfg=` argument that could receive a dict with config overrides (from any source, not necessarily a `ConfigManager` only. Those overrides would be taken into account in `_get_adjusted_env()` for the subprocess. Thereby each caller could select the most appropriate `ConfigManager` for a specific use case.

**Comment by christian-monch** [comment]
A quick comment on:

> The simplest approach that I can see is therefore completely unrelated to the `ConfigManager`.
> 
> * on CLI startup: read `-c`, merge them with any Git config ENV overrides, and repost them to the ENV before anything else happens. Possibly include `DATALAD_CONFIG_OVERRIDES_JSON` in that procedure.
> * enhance `Runner.run()` with a `cfg=` argument that could receive a dict with config overrides (from any source, not necessarily a `ConfigManager` only. Those overrides would be taken into account in `_get_adjusted_env()` for the subprocess. Thereby each caller could select the most appropriate `ConfigManager` for a specific use case.

Seems sensible to me.
