### ISSUE TITLE
FAILED test_clone.py::test_autoenabled_remote_msg

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#331]
This is tripping the datalad-core test battery. It was fixed in datalad-core with https://github.com/datalad/datalad/pull/7367, but there has been no release.

We could consider switching the version of datalad-core to be tested here to the most recent state of its `maint`. This would be useful for development, but not for checking whether datalad-next's dependency declaration is fit-for-release.

In general https://github.com/datalad/datalad-extensions should provide insight, but it does not test the released datalad-core, and we only know about the continued failure in a released version, because here we test the latest datalad-core release (with datalad-next enabled).

**Comment by adswa** [comment]
I think one possible way to tackle this is to adopt a faster release cycle in datalad. Yarik mentioned it in the past, pointing to how they do it in DANDI - essentially with every merged PR.

**Comment by mih** [comment]
0.18.4 is out. We can undo to tmp fix.
