### ISSUE TITLE
Add `EnsureHashAlgorithm`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#346]
There is detection logic in `MultiHash` that could/should become exposed in this more standard fashion. For commands that support it (`download`, `ls-file-collection`) it would also make sense to implement `EnsureMultiHash`

**Comment by mslw** [comment]
`MultiHash` uses hashlib, and hashlib provides constant attributes `hashlib.algorithms_guaranteed` ([doc](https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_guaranteed)) and `hashlib.algorithms_available` (both sets) - seems like a perfect fit.

**Comment by mslw** [comment]
TIL from [hashlib docs](https://docs.python.org/3.11/library/hashlib.html):

> `hashlib.algorithms_available`: A set containing the names of the hash algorithms that are available in the running Python interpreter. These names will be recognized when passed to `new()` [but have no named constructors in hashlib -- mslw]
> 
> `hashlib.new` Is a generic constructor that takes the string name of the desired algorithm as its first parameter. It also exists to allow access to the above listed hashes as well as any other algorithms that your OpenSSL library may offer. The named constructors are much faster than `new()` and should be preferred.

So with the way `MultiHash` currently works (`hr = getattr(hashlib, h.lower(), None)`), we need to check against `algorithms_guaranteed`.

We could also extend `MultiHash` to use the additional ones through `new()` if not found in attributes. However, we probably care much less about the non-guaranteed algorithms. This is what's guaranteed and additionally available on my laptop:

``` pycon
>>> import hashlib
>>> hashlib.algorithms_guaranteed
{'shake_256', 'sha224', 'sha3_512', 'md5', 'sha3_256', 'sha3_224', 'shake_128', 'sha3_384', 'sha512', 'sha384', 'blake2s', 'blake2b', 'sha1', 'sha256'}
>>> hashlib.algorithms_available - hashlib.algorithms_guaranteed  # set difference
{'sm3', 'md4', 'ripemd160', 'sha512_256', 'whirlpool', 'md5-sha1', 'sha512_224'}
```

And example usage:
```pycon
>>> hasattr(hashlib, "ripemd160")
False
>>> h = hashlib.new("ripemd160")   # must go through new
>>> h.update(b"Nobody inspects the spammish repetition")
>>> h.hexdigest()
'cc4a5ce1b3df48aec5d22d1f16b894a0b894eccc'
```

I will probably use `algorithms_guaranteed` for now.

**Comment by mslw** [comment]
Trying to build `EnsureHashAlgorithm` as a naive `EnsureChoice` derivation (see draft PR above) and testing on `ls-file-collection`, I noticed that hash names are already coerced to a list (by `joint_constraints` if I'm reading correctly) when they reach `param_constraints`:

```
❱ datalad ls-file-collection --hash md5 directory foo
[ERROR  ] 1 command parameter constraint violation
hash=['md5']
  is not one of ({'sha3_224', 'sha3_384', 'shake_128', 'sha3_256', 'sha1', 'sha256', 'shake_256', 'sha3_512', 'sha512', 'sha224', 'md5', 'blake2b', 'blake2s', 'sha384'},)
```

I just wanted to confirm whether this is an intended behavior, and ask about the correct way to implement the constraint - should it handle a list, or handle a single item, but be somehow wrapped inside `parameter_constraints`?

**Comment by mslw** [comment]
I was doubly wrong in my comment above:
- When coming from CLI, `hash` is a list, because it is a parameter with `--append` (argparse behavior). The order of validation is fine (first `param_constraints`, then `joint_constraints`). When coming from CLI it can be a string.
- I also took too much of a shortcut with `EnsureChoice` - the error message shows that my constraint compared againist the entire set, not set elements.

I think I've got it now - parameter constraint should expect a string, but the command should get `EnsureHashAlgorithm | EnsureIterableOf(EnsureHashAlgorithm)` :smile:

**Comment by mih** [comment]
@mslw 

> `EnsureHashAlgorithm() | EnsureListOf(EnsureHashAlgorithm)` passes valid inputs correctly, but the combination is not perfect when it comes to error messaging

The approach is good. That the messaging is suboptimal exposes two issues:

1. the self-description of `EnsureChoice` is not good
2. the error handling of `EnsureIterableOf` is not good enough

The following diff sketches a solution to both issues. I have not checked what would break when applied in general, but in your PR this changes the error message to

```
❯ datalad ls-file-collection --hash abc directory .
[ERROR  ] 1 command parameter constraint violation
hash=['abc']
  does not match any of 2 alternatives
    - is not one of ('md5', 'shake_256', 'sha512', 'sha3_224', 'sha3_384', 'sha256', 'blake2b', 'sha384', 'sha3_512', 'sha1', 'sha224', 'shake_128', 'blake2s', 'sha3_256')
    - list item is not one of {'md5', 'shake_256', 'sha512', 'sha3_224', 'sha3_384', 'sha256', 'blake2b', 'sha384', 'sha3_512', 'sha1', 'sha224', 'shake_128', 'blake2s', 'sha3_256'} 
```

**Comment by mih** [comment]
This was added in #492
