### ISSUE TITLE
`datalad save -m` siliently discards multiple invocations

### ISSUE THREAD

**Issue by aqw** [datalad/datalad-next#354]
I ran a `datalad save` command similar to the following:
```
datalad save -m 'subject' -m 'body'
```

However, the result was that `-m 'subject'` was silently ignored and `body` became the subject.

I had assumed that `datalad save` would follow `git commit`'s behavior here. The git commit manpage has this section:
```
-m <msg>, --message=<msg>
    Use the given <msg> as the commit message. If multiple -m options are given,
    their values are concatenated as separate paragraphs.
```

For kicks, I tried the workaround `datalad save -m "subject\n\nbody"`, but that results in the subject being literally `subject\n\nbody`.

Declaring `-m` multiple times is perhaps an oft-overlooked feature, but I personally find it useful in the situations where I don't want to spawn an interactive editor, but still wish to provide a comprehensive commit message (without generating a separate file to pass to `-F`).

Whether datalad chooses to support this feature or not, I feel that exiting with an error is more appropriate than the present behavior. Commit messages may not be normally considered as "data", but the commit message and body(s) are annotations supplied by the user, and the present behavior silently discards it.

**Comment by mih** [comment]
Supporting that makes sense to me, and I would suspect it to be a relatively simple change. Thanks for the suggestion!

**Comment by adswa** [comment]
One way to do it in the argparse framework that core and next use would be with

```diff
diff --git a/datalad/interface/common_opts.py b/datalad/interface/common_opts.py
index 18a81ad26..bff5d42c8 100644
--- a/datalad/interface/common_opts.py
+++ b/datalad/interface/common_opts.py
@@ -152,6 +152,8 @@ save_message_opt = Parameter(
     args=("-m", "--message",),
     metavar='MESSAGE',
     doc="""a description of the state or the changes made to a dataset.""",
+    action='extend',
+    nargs='*',
     constraints=EnsureStr() | EnsureNone())
```

Every command in core with an ``-m`` option would need to then implement appropriate handling of the resulting list, e.g., 

```
diff --git a/datalad/core/local/save.py b/datalad/core/local/save.py
index 6a193f2ae..2a6489c8e 100644
--- a/datalad/core/local/save.py
+++ b/datalad/core/local/save.py
@@ -175,6 +175,8 @@ class Save(Interface):
         if message and message_file:
             raise ValueError(
                 "Both a message and message file were specified for save()")
+        if message:
+            message = '\n'.join(message)
```

I think in next, parameter validation could handle this, maybe with a new constraint in compounds.py that transforms the list of message(s) into a string.

**Comment by mih** [comment]
https://hub.datalad.org/datalad/dlcmd now implements multiple `-m` for `save`. It concatenates the message into multiple paragraphs, just as `git commit` does.

**Comment by aqw** [comment]
Great!! :-D
