### ISSUE TITLE
Type annotations of `TarArchiveOperations.open` are not correct

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-next#406]
This is an issue that is "caused" by the use of the `contextmanager`-decorator in the definition of the method `TarArchiveOperations.open`. 

The body of the implementation of `TarArchiveOperations.open()` returns a generator, since it uses a `yield`-statement. In combination with the `@contextmanager`-decorator the `open()`-method on an instance becomes a method that returns an `IO`-object. So, any caller of `open()` on a `TarArchiveOperations`-instance will see a return value that is an instance of `IO`.

The doc-strings should document the behavior that is observed on an instance of `TarArchiveOperations`.

But if we introduce type-checking, the annotations for the return-value, i.e. `IO`, will trigger an error, because the real return-type of the function specified by the code in `TarArchiveOperations.open()` is `Generator[IO, None, None]`.

There are a few options to mitigate the problem:

1. Do not introduce type-checks and ignore the discrepancy
2. Introduce type-checks, but ignore this particular definition (not sure if that is possible for all type checkers)
3. Correct the type annotation in the code, document the behavior of instances in the doc-string.

I would prefer option 3. The code annotations would be correct, and the documentation of the behavior of `open()` on instances of `TarArchiveOperations` would also be correct.

**Comment by mih** [comment]
This is probably also the answer to https://github.com/datalad/datalad-next/issues/363
