### ISSUE TITLE
Question about order of steps in `EnsureCommandParameterization`

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-next#429]
I was initially under the (wrong?) impression that the `EnsureCommandParameterization`-inheriting validator for a `ValidatedInterface` does things in the following order:

1. individual parameter validation, where an arbitrary set of constraints can be applied and where a possibly updated parameter is then passed to the next step
2. `joint_validation`, which itself could have multiple sets of `ParameterConstraintContext` which are applied in the order that they are specified, each passing possibly updated parameters to the following.
3. lastly, passing of validated parameters to the `ValidatedInterface`'s `__call__` function, which would apply defaults from the command signature.

But, I saw in a simple test case that the default was already applied to a parameter by the time it got the `joint_validation`. Is this intended? Is there somewhere in the next code where the order and reasoning is made more clear? I read through the `EnsureCommandParameterization` docstrings but couldn't find something that made sense to me.

**Comment by mih** [comment]
re 1: with `validate_defaults` set, this would already make a default  value subject to validation. If not set, the default value becomes/stays the argument as-is.

Everything else follows from that.

> in a simple test case that the default was already applied to a parameter by the time it got the joint_validation

The default value has been the argument value from the get go. The only thing that did not happen is a transformation by a constraint, it was merely kept as is (unless `validate_defaults` is set).

So when it gets to `joint_validation` the default remains the value, and that is subject to joint validation. There is no "re-apply the default after some other processing". I would not know how this could be done in a meaningful fashion, or have a use case where this would make sense.

The key code piece is:

https://github.com/datalad/datalad-next/blob/e22b87101675b154b80aba4a4030b460ee312b7f/datalad_next/constraints/parameter.py#L315-L333

**Comment by jsheunis** [comment]
ok this makes more sense now, thank you.
