### ISSUE TITLE
Add note about (to be) deprecated test fixtures

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-next#448]
> In datalad_next/tests/utils.py you can see the full list of these old helpers that still have (some) purpose. But mostly also "did not get to it yet". Anything that is not in that list, should not be touched

Add a note to this effect so that developers can know which fixtures to use and not to use, and which ones to try and migrate to using pytest built-ins.

**Comment by adswa** [comment]
Could go into the CONTRIBUTING guide, which is what the "developer guide" links to: https://github.com/datalad/datalad-next/blob/main/CONTRIBUTING.md

**Comment by mih** [comment]
There are already rules on imports and limits to imports from core.
