### ISSUE TITLE
Implement `iterannexworktree()` for `ls-file-collection`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#459]
Somewhat related to #349, we have a need to report on annex-managed (work)tree in the shape of an iterator.

We have four substantially overlapping implementations that provide a closely related functionality:

1. `AnnexRepo.get_content_annexinfo()` (from datalad-core)
2. `gooey-status-light` (from datalad-gooey): motivation for its implementation was to achieve a substantially faster performance than `get_content_annexinfo()`
3. https://github.com/datalad/datalad-metalad/blob/dev_0.5/iter_test/iterate_dataset.py (motivation for implementation not yet determined)
4. https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/48 (motivation for implementation not yet determined)

These for need to be investigated re functionality and performance. Ideally, one and only one implementation should be used instead.

**Comment by mih** [comment]
A first pass through that code leads me to conclude that (1) and (3) are tightly dependent on a large stack of surrounding code/assumptions. It could be difficult to detach them from their respective habitats.

(2) and (4) are simplistic, posing the questions whether they are implemented robust enough to handle real-world use cases.

A next step would be to define what would be needed from such an iterator.

**Comment by mih** [comment]
Performance considerations:

Performance characterization for (4): https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/48#issuecomment-1741358934

Running a bunch of approaches on the same test dataset (36k annexed files, locally present content, total size 850MB):

(1) via `datalad --status annex`: 10s

Example output:

```json
{"action": "status",
 "backend": "MD5E",
 "bytesize": 21040,
 "gitshasum": "88cfe27d24310e2790bff62cf6ea30b595bf6cbd", 
"hashdirlower": "c3f/0b3/",
 "hashdirmixed": "33/jF/",
 "humansize": "21.04 kB",
 "key": "MD5E-s21040--8e85cfb8b7994855a6fd0ed25936415a",
 "keyname": "8e85cfb8b7994855a6fd0ed25936415a",
 "mtime": "unknown",
 "parentds": "/home/mih/dcm",
 "path": "/home/mih/dcm/study_20140724_095117357/MR.1.3.46.670589.11.38317.5.0.4480.2014071811194049116",
 "prev_gitshasum": "88cfe27d24310e2790bff62cf6ea30b595bf6cbd", 
"refds": "/home/mih/dcm",
 "state": "clean",
 "status": "ok",
 "type": "file"}
```

#### (2) `datalad -f json gooey-status-light -d . study_20140724_095117357`: 7s

This command is artificially limiting its output to match a single directory only. The reporting is nevertheless on 36k annexed files.

```json
{"action": "status",
 "bytesize": "21040",
 "hashdirlower": "584/e41/",
 "hashdirmixed": "KX/vf/",
 "key": "MD5E-s21040--4976b2cf494e6b7f101608eeea296d53",
 "path": "/home/mih/dcm/study_20140724_095117357/MR.1.3.46.670589.11.38317.5.0.4480.2014071811222205472",
 "refds": "/home/mih/dcm",
 "state": "clean",
 "status": "ok",
 "symlink_target": "../.git/annex/objects/KX/vf/MD5E-s21040--4976b2cf494e6b7f101608eeea296d53/MD5E-s21040--4976b2cf494e6b7f101608eeea296d53", "type": "file"}
```

#### (4)  `python list_files.py . outf.txt`: 4min 44s

Example output:

```json
{"type": "file",
 "dataset_id": "e8bf45ec-a532-11e7-be92-f0d5bf7b5561",
 "dataset_version": "17cf7dea78eeeaff2da302e2ab4ce3c9d8f66039", 
"path": "study_20140724_095117357/MR.1.3.46.670589.11.38317.5.0.4480.2014071811122409435", 
"contentbytesize": 212600}
```


#### iterator-based comparison

- `datalad -f json ls-file-collection gitworktree . --hash md5`: 6s
- `datalad -f json ls-file-collection gitworktree . --hash md5`: 2s


I was not yet able to get (3) to run.

We can consider (1) to deliver a superset of relevant information Any new implementation should therefore for substantially faster than 10s on this test dataset.

**Comment by mih** [comment]
### Design/functionality

After reading a bit into the respective implementations, I propose the following properties for the coming implementation

- companion to `gitworktree` iterator (i.e., no state/change detection functionality that e.g. `gooey-status-light` provides, but a mere reporting of what is in the worktree)
- implementation can follow `gooey-status-light` by wrapping a generator (here `iter_gitworktree`), and amend its reports with previously gathered annex-properties
- worth considering: implement `include/exclude` logic already for the base iterator (and matching for the annex property gatherer). This would yield a better fit for the `gooey` use case of just wanting to report on a single directory (without subdirs; already used in `gooey-status-light`). Anticipated implementation complexity for such a filter is minimal (regex matching of paths, which are already at the center of the iterator loop).
- it also makes sense to support `fp: bool` as an iterator argument, to provide direct access to a (linked) files in the annex.

**Comment by mslw** [comment]
FTR (4) has now been retired in favour of `datalad status --annex basic` which indeed reports all the information (path + size of each file, regardless if annexed or not) that I cared about. The motivation was my initial misunderstanding of the `status` command.

I suppose that the motivation for (3) might have been to integrate with MetaLad's dataset / file traversers that can be used with other metadata extractors as well?

> ... I propose the following properties for the coming implementation
> companion to gitworktree iterator (i.e., no state/change detection functionality that e.g. gooey-status-light provides, but a mere reporting of what is in the worktree)

I think this is a good framing. If I see it correctly, the `gitworktree` operator reports symlinked annex content as symlinks, making it harder to access actual properties (e.g. size) of the annexed file. The annexworktree operator coould be aware of those.

> (3) and (4) report constant properties (e.g., dataset ID). This should not be done, it is both easier and faster to gather this information outside the iterator (if it is even needed for a particular use case).

Agree.

**Comment by mih** [comment]
Done via https://github.com/datalad/datalad-next/pull/539
