### ISSUE TITLE
`ls_file_collection` does not support zipfile

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-next#472]
Although `datalad_next.iter_collections.zipfile` is available, the high-level API command, `ls_file_collection`, does not support it.

It seems to me that to be supported, the `zipfile` collection requires:
- its corresponding `iter_fx` and `item2res` to be declared / defined
- "zipfile" to be added to `_supported_collection_types`
- `ls_file_collection` docstring to be extended

Was the omission intentional, or was it simply not enabled?

Potentially related #430 and #470

**Comment by mih** [comment]
Still the case. All linked issues are resolved, but the integration into `ls-file-collection` is simply not done yet.

**Comment by mih** [comment]
PR with the essentials is posted now.
