### ISSUE TITLE
Replace `www-authenticate`

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#493]
We need this as a dependency for #490. However, packaging it for Debian seems like overkill. The whole thing is ~80 lines of code in a single file.

The last update was 8 years ago.

I would consider adopting a copy, unless @basilgello has other preferences.

**Comment by mih** [comment]
Actually no. The code is covered by an old version of the BSD license https://github.com/alexdutton/www-authenticate/commit/a35e5df38d909e0f73bb6df0573fa80333a4922e

This license does not specifically permit modification. Wikipedia suggests that it is nevertheless DFSG-compatible, but it may be worth looking for an alternative.

**Comment by basilgello** [comment]
I did that one: https://salsa.debian.org/python-team/packages/python-www-authenticate

As I told to @yarikoptic we need to upload stuff to Debisn and I am only a DM so DD sponsorship is needed.

Lets chat in CON Matrix room and let me update all other pkgs
