### ISSUE TITLE
Contributor setup

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#507]
While working on the Debian packaging I noticed that datalad-next does not have the contributor recording setup of other extensions. It would be nice to get that and have a valid contributor record.

**Comment by adswa** [comment]
I requested the allcontributors bot to be installed in this repo. Once done, I can also add the tributors update workflow that datalad core uses. I'm pushing  a manual amendment to zenodo.json in  a second

**Comment by mih** [comment]
I approved the request
