### ISSUE TITLE
`iter_annexworktree` fails on Windows 10 with git-annex 

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-next#559]
On a Windows installation (Windows 10Pro, 22H2) with git-annex version: 10.20230803-gd467c70ef7, the tests of  `iter_annexworktree` fail. 

The reason is that a key in the format `'${key}\r\n'` is written out by git-annex find, even though the format `'${key}\n'` is specified (the output contains an additional `'\r'`).

The `itemize`-function that parses the output of git-annex find expects a single `b'\n'` as key-terminator, and fails therefore to properly yield individual keys.

This can be fixed by setting the terminator to `None` which allows `itemize` to use a number of different separators, e.g. `b'\r'` and `b'\r\n'`.

**Comment by mih** [comment]
Fix with #560
