### ISSUE TITLE
Reenable GITEA tests

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#608]
The try.gitea.io site shows strangely similar behavior to #604

I disabled the associated tests by renaming the TOKEN secret on appveyor.

Once the site is back to normal, we need to re-enable these tests.

**Comment by adswa** [comment]
this will be possible with https://github.com/datalad/datalad/pull/7638

**Comment by adswa** [comment]
The tests are now possible: The Appveyor secret has been renamed to reenable them. The demo Gitea space has been moved from try.gitea.io to demo.gitea.com, and this changed has been merged to datalad-core in https://github.com/datalad/datalad/pull/7638. Once datalad is released (hopefully with https://github.com/datalad/datalad/pull/7636) the GITEA test should pass
