### ISSUE TITLE
Handle global option `-c` properly

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-next#677]
The following cmdline fails with a `TypeError` in datalad-next:

```
datalad -c :mike.item configuration mike.item
``` 

PR #669  contains a fix for the `TypeError`, but the following issues remain in datalad-next:

1. unsetting an existing configuration key with global option `-c :<key>` does not unset the key properly. The command `datalad -c :some.key configuration get some.key` will report an empty string value for `some.key`.
2. unsetting a non-existing configuration key with global option `-c :<non-existing-key>` will make the key available to datalad with a value of empty-string. The command `datalad -c :<non-existing-key> configuration get <non-existing-key>` will report an empty string value for `<non-existing-key>`, although it was never set.

The outlined behavior seems incorrect. In the first case, an `impossible`-error should be returned, stating that the key cannot be retrieved.
In the second case, either an `impossible`-error that states that the key cannot be retrieved or a different error that states that non-existing keys cannot be unset by option `-c` should be returned.

**Comment by mih** [comment]
I agree with the assessment. The situation is unfortunate and possibly not really solvable.

Git does not support unsetting config keys via the environment (or any method other than unsetting in a dedicated call, at a specific scope).

This means that we could only employ some kind of special (str-type) label to indicate that a value is to be considered unset. But this is essentially a more sophisticated implementation of the status quo (we set a value for something that is not supposed to be set at all). Thereby we introduce ambiguity and fragility. We could make a query via the `ConfigManager` to do the right thing, but any query via Git would come to a different conclusion.

Right now I think we need to update the documentation that this feature has a very limited scope (unset for queries via `ConfigManager` in the root process), and, likely, that we are deprecating this feature entirely.

**Comment by christian-monch** [comment]
> I agree with the assessment. The situation is unfortunate and possibly not really solvable.
> [...]
> ```
> datalad -c :mike.item configuration get mike.item
>[WARNING] Ignoring non-str "mike.item" config key value None 
>myvalue
>```
> [...]

IMHO this behavior is even more confusing, i.e. a git config-key is set, e.g. to `myvalue`, the option `-c :mike.item` instructs datalad to unset it, but the datalad command `configuration get mike.item` retrieves the original value, i.e. `myvalue`. 

(I made the same changes in my PR earlier, but dismissed the approach due to the confusing output. Furthermore it would fail one of the config-tests.)
