### ISSUE TITLE
`pytest` now unintentional runtime dependency

### ISSUE THREAD

**Issue by mih** [datalad/datalad-next#698]
Look here: https://ci.debian.net/packages/d/datalad-next/testing/amd64/46884776/#S4

A plain import now requires `pytest`. This is due to the datalad-core patch fixing up some tests that was introduced with https://github.com/datalad/datalad-next/pull/669

This needs to be undone.

Ping @christian-monch for awareness.

**Comment by aqw** [comment]
It might be possible to guard the import of the patch to detect if [pytest is running](https://doc.pytest.org/en/latest/example/simple.html#detect-if-running-from-within-a-pytest-run):

```
import os
if os.environ.get("PYTEST_VERSION") is not None:
    import pytest
```

Or alternatively `sys._called_from_test`.
