### ISSUE TITLE
Get ZENODO DOI for releases

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-next#79]
I would like to be able to cite this software. Could we create a CITATION.cff file or make release on ZENODO to Doi-ify it? Then I can properly reference it in a proceedings contribution that is due on July 15th. Thanks

**Comment by adswa** [comment]
Thanks much @mslw! My thoughts are:
- Zenodo generally makes a lot of sense, since almost all other datalad extensions are published like this
- That being said, Zenodo requires are release, as far as I know
- However, Zenodo ingests CITATION.cff files, so generating one would allow me to cite the software properly on short notice and result in a Zenodo publication once released. There even is an online generator for it: https://citation-file-format.github.io/cff-initializer-javascript
- I think it would make a lot of sense to have more people with admin access to the project so that work like this can be done easily, without waiting on others and with less gate keeping. Ping @mih - can you make frequent contributors like @mslw admin here?

**Comment by mih** [comment]
@mslw is admin now.

Please note that a -next release needs a datalad 0.17 release, and https://github.com/datalad/datalad-next/pull/73 merged.

**Comment by mslw** [comment]
I think I messed up a little, in that I waited for the release before enabling this project on Zotero. I only flipped the switch now. But the [FAQ](https://help.zenodo.org/) says that "Only the repositories which were enabled before a release was made will be archived automatically".

What's the course of action? Should I make a manual zip upload of 0.4.0?

**Comment by mih** [comment]
Done: https://zenodo.org/record/6833100 and 10.5281/zenodo.6833100

Thx much to all!
